name: test

on:
  push:
  pull_request:

env:
  BUNDLE_JOBS: 4
  BUNDLE_RETRY: 3
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.7.6
          - 3.0.4
          - 3.1.2
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Ragel
      run: |
        sudo apt-get update
        sudo apt-get install ragel

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake
